version: '3.3'
services:
  tracer:
    entrypoint: [ "/start-reload.sh" ]
    build:
      context: ./service
    environment:
      - SERVER_HOST=http://${BACKEND_DOMAIN_NAME}
      - SERVER_NAME=${BACKEND_DOMAIN_NAME}
      - VIRTUAL_HOST=${BACKEND_DOMAIN_NAME}
      - BACKEND_CORS_ORIGINS=["http://localhost", "http://localhost:4200", "https://localhost", "https://localhost:4200",  "https://localhost:8080", "http://api.dev.tracer.io"]
      - PROJECT_NAME=tracer
      - POSTGRES_SERVER=db
      - POSTGRES_USER=tracer
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    ports:
      - "8080:8080"
    env_file:
      - .local.env
      - .common.env
    volumes:
      - ./service/app:/app

    depends_on:
      - db
    networks:
      default:
        aliases:
          - ${BACKEND_DOMAIN_NAME}
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'
  db:
    ports:
      - '5432:5432'
    image: postgres:11
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=tracer
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    networks:
      default:
        aliases:
          - ${BACKEND_DOMAIN_NAME}

  celeryworker:
    build:
      context: ./service
      dockerfile: Dockerfile.celery
    environment:
      - SERVER_HOST=http://${BACKEND_DOMAIN_NAME}
      - SERVER_NAME=${BACKEND_DOMAIN_NAME}
      - VIRTUAL_HOST=${BACKEND_DOMAIN_NAME}
      - BACKEND_CORS_ORIGINS=["http://localhost", "http://localhost:4200", "https://localhost", "https://localhost:4200",  "https://localhost:8080", "http://api.dev.tracer.io"]
      - PROJECT_NAME=tracer
      - POSTGRES_SERVER=db
      - POSTGRES_USER=tracer
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    env_file:
      - .local.env
      - .common.env
    volumes:
      - ./service/app:/app
