"""initial migration

Revision ID: 91fd165948fb
Revises: 
Create Date: 2022-01-12 10:48:18.316939

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "91fd165948fb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "block_trace",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("block_number", sa.Numeric, nullable=False),
        sa.Column("block_timestamp", sa.Numeric, nullable=False),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("block_number"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("block_trace")
