"""initial migration

Revision ID: 91fd165948fb
Revises: 
Create Date: 2022-01-12 10:48:18.316939

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import UUID

revision = "91fd165948fb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "block",
        sa.Column("block_number", sa.Integer, nullable=False, index=True, primary_key=True),
        sa.Column("block_timestamp", sa.Integer, nullable=False, index=True),
        sa.UniqueConstraint("block_number"),
    )

    op.create_table(
        "block_trace",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("block_hash", sa.String, index=True),
        sa.Column("block_number", sa.Integer, nullable=False, index=True),
        sa.Column("action", sa.JSON),
        sa.Column("result", sa.JSON, nullable=True),
        sa.Column("subtraces", sa.Integer),
        sa.Column("trace_address", sa.ARRAY(sa.Integer), nullable=False),
        sa.Column("transaction_hash", sa.String),
        sa.Column("transaction_position", sa.Integer),
        sa.Column("type", sa.String),
        sa.Column("error", sa.String, nullable=True),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("block_trace")
