FROM python:3.7-slim as base

RUN useradd -ms /bin/bash user --home /app

WORKDIR /app
ENV PYTHONPATH=/app

COPY reqs/base.txt requirements.txt

RUN pip install -U setuptools pip
RUN pip install -r requirements.txt


FROM base as run

COPY app /app
COPY ./app/worker-start.sh /worker-start.sh

RUN chmod +x /worker-start.sh

CMD ["bash", "/worker-start.sh"]

