name: dev - Full Deployment

on:
  push:
    branches:
      - main

jobs:
  infra-setup:
    name: Setup Infra
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform apply
        run: ENV=infra make infra

  build-tracer-service:
    name: Build - Tracer Service
    runs-on: ubuntu-18.04
    needs:
      - infra-setup
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build
        run: make docker-build-service

      - name: Push
        run: make docker-push-service

  build-tracer-celery:
    name: Build - Tracer Celery
    runs-on: ubuntu-18.04
    needs:
      - infra-setup
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build
        run: make docker-build-celery

      - name: Push
        run: make docker-push-celery

  unit-tests-tracer:
    name: Unit Tests - tracer
    runs-on: ubuntu-18.04
    needs:
      - build-tracer-service
      - build-tracer-celery
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Docker Tests
        run: echo "Not implemented yet"


  deploy-to-dev-full:
    name: Deploy to dev - full
    runs-on: ubuntu-18.04
    needs:
      - unit-tests-tracer
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Deploy
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          RPC_URL: ${{ secrets.RPC_URL }}
        run: ENV=dev make deploy
