name: dev - Full Deployment

on:
  push:
    branches:
      - main

jobs:
  infra-setup:
    name: Setup Infra
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Validate
        run: ENV=infra make infra

  build-tracer:
    name: Build - tracer
    runs-on: ubuntu-18.04
    needs:
      - infra-setup
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build
        run: make docker-build

      - name: Push
        run: make docker-push

  unit-tests-tracer:
    name: Unit Tests - tracer
    runs-on: ubuntu-18.04
    needs:
      - build-tracer
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Docker Tests
        run: echo "Not implemented yet"


  deploy-to-dev-full:
    name: Deploy to dev - full
    runs-on: ubuntu-18.04
    needs:
      - unit-tests-tracer
      - build-tracer
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Deploy
        run: ENV=dev echo "1234"
