name: dev - Full Deployment

on:
  push:
    branches:
      - main

jobs:
  build-tracer:
    name: Build - tracer
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.DEPLOYER_AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Build
        run: make docker-build

      - name: Push
        run: make docker-push


  build-celery-worker:
    name: Build - deployment-api
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.DEPLOYER_AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Build
        run: make docker-build-celery

      - name: Push
        run: make docker-push-celery


  unit-tests-tracer:
    name: Unit Tests - tracer
    runs-on: ubuntu-18.04
    needs:
      - build-tracer
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.DEPLOYER_AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Docker Login
        run: make docker-login

      - name: Lint
        run: make docker-lint-tracer

      - name: Test
        run: make docker-unit-tests-tracer


  deploy-to-dev-full:
    name: Deploy to dev - full
    runs-on: ubuntu-18.04
    needs:
      - unit-tests-tracer
      - unit-tests-celery
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.DEPLOYER_AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Terraform Validate
        run: echo "only if time permits"  # ENV=dev make deploy
